name: Amazon ECS Down
description: Halts a running Amazon ECS contianer via docker compose
inputs:
  aws-access-key-id:
    description: secret AWS access key ID
    required: true
  aws-region:
    description: preferred AWS region, e.g. us-east-2
    required: true
  aws-secret-access-key:
    description: secret AWS access key
    required: true
  docker-compose-path:
    description: path to Docker compose YAML file defining ECS deployment config
    required: true
  ecr-repository:
    description: Amazon ECR repository name
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Bring down container
      env:
        ECR_IMAGE_URL: ${{ format('{0}/{1}', steps.login-ecr.outputs.registry, inputs.ecr-repository) }}
      run: |
        docker context create ecs deploy --from-env
        docker context use deploy
        docker compose -f ${{ inputs.docker-compose-path }} down
      shell: bash
